import 'package:flutter/material.dart';

class AppColorScheme {
  static ColorScheme lightScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff804d7a),
      surfaceTint: Color(0xff804d7a),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xffffd7f5),
      onPrimaryContainer: Color(0xff653661),
      secondary: Color(0xff6d5869),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xfff7daef),
      onSecondaryContainer: Color(0xff554151),
      tertiary: Color(0xff825345),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xffffdbd1),
      onTertiaryContainer: Color(0xff663c2f),
      error: Color(0xffba1a1a),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffffdad6),
      onErrorContainer: Color(0xff93000a),
      surface: Color(0xfffff7f9),
      onSurface: Color(0xff201a1e),
      onSurfaceVariant: Color(0xff4e444b),
      outline: Color(0xff80747c),
      outlineVariant: Color(0xffd1c2cb),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff352e33),
      inversePrimary: Color(0xfff1b3e6),
      primaryFixed: Color(0xffffd7f5),
      onPrimaryFixed: Color(0xff340832),
      primaryFixedDim: Color(0xfff1b3e6),
      onPrimaryFixedVariant: Color(0xff653661),
      secondaryFixed: Color(0xfff7daef),
      onSecondaryFixed: Color(0xff271624),
      secondaryFixedDim: Color(0xffdabfd2),
      onSecondaryFixedVariant: Color(0xff554151),
      tertiaryFixed: Color(0xffffdbd1),
      onTertiaryFixed: Color(0xff321208),
      tertiaryFixedDim: Color(0xfff5b8a7),
      onTertiaryFixedVariant: Color(0xff663c2f),
      surfaceDim: Color(0xffe3d7dd),
      surfaceBright: Color(0xfffff7f9),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfffdf0f7),
      surfaceContainer: Color(0xfff7ebf1),
      surfaceContainerHigh: Color(0xfff1e5eb),
      surfaceContainerHighest: Color(0xffecdfe5),
    );
  }
  static ColorScheme darkScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xfff1b3e6),
      surfaceTint: Color(0xfff1b3e6),
      onPrimary: Color(0xff4c1f49),
      primaryContainer: Color(0xff653661),
      onPrimaryContainer: Color(0xffffd7f5),
      secondary: Color(0xffdabfd2),
      onSecondary: Color(0xff3d2b3a),
      secondaryContainer: Color(0xff554151),
      onSecondaryContainer: Color(0xfff7daef),
      tertiary: Color(0xfff5b8a7),
      onTertiary: Color(0xff4c261b),
      tertiaryContainer: Color(0xff663c2f),
      onTertiaryContainer: Color(0xffffdbd1),
      error: Color(0xffffb4ab),
      onError: Color(0xff690005),
      errorContainer: Color(0xff93000a),
      onErrorContainer: Color(0xffffdad6),
      surface: Color(0xff171216),
      onSurface: Color(0xffecdfe5),
      onSurfaceVariant: Color(0xffd1c2cb),
      outline: Color(0xff9a8d95),
      outlineVariant: Color(0xff4e444b),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffecdfe5),
      inversePrimary: Color(0xff804d7a),
      primaryFixed: Color(0xffffd7f5),
      onPrimaryFixed: Color(0xff340832),
      primaryFixedDim: Color(0xfff1b3e6),
      onPrimaryFixedVariant: Color(0xff653661),
      secondaryFixed: Color(0xfff7daef),
      onSecondaryFixed: Color(0xff271624),
      secondaryFixedDim: Color(0xffdabfd2),
      onSecondaryFixedVariant: Color(0xff554151),
      tertiaryFixed: Color(0xffffdbd1),
      onTertiaryFixed: Color(0xff321208),
      tertiaryFixedDim: Color(0xfff5b8a7),
      onTertiaryFixedVariant: Color(0xff663c2f),
      surfaceDim: Color(0xff171216),
      surfaceBright: Color(0xff3e373c),
      surfaceContainerLowest: Color(0xff120d11),
      surfaceContainerLow: Color(0xff201a1e),
      surfaceContainer: Color(0xff241e22),
      surfaceContainerHigh: Color(0xff2f282d),
      surfaceContainerHighest: Color(0xff3a3338),
    );
  }
}