name: flutterarchitecture
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.10.0
#----------------------------
#----------------------------
#----------------------------
dependencies:
  flutter_localizations:
    sdk: flutter

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #  prerequisite
  google_fonts: ^6.3.2
  provider: ^6.1.5
  dio: ^5.9.0
  get_it: ^9.2.0

  #  firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_messaging: ^16.1.0
  cloud_firestore: ^6.1.0
  google_sign_in: ^6.2.1
  
  #  remote database
  # mongo_dart: ^0.10.5

  #  connectivity service
  # connectivity_plus: ^7.0.0
  # socket_io_client: ^3.1.4

  #  local worker
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  crypto: ^3.0.7
  flutter_secure_storage: ^10.0.0

  #  media
  flutter_svg: ^2.0.10+1
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  image_picker: ^1.0.7
  file_picker: ^10.3.8

  #  ui
  pinput: ^6.0.0
  font_awesome_flutter: ^10.12.0
  intl: ^0.20.2
  # google_nav_bar: ^5.0.7


  #----------------------------
  #----------------------------
  #----------------------------
  flutterprovider:
    path: ../flutterprovider
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  analyzer: ^6.4.1
  hive_generator: ^2.0.1

  # added
  build_runner: ^2.4.8
  flutter_gen_runner: 5.3.2


  #  app icons
  flutter_launcher_icons: ^0.13.1
#----------------------------
#----------------------------
#----------------------------
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/audios/
    - assets/gifs/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/illustrations/
    - assets/jsons/
    - assets/lottiefiles/
    - assets/texts/
    - assets/lang/
    - assets/videos/
#----------------------------
#----------------------------
#----------------------------

flutter_native_splash:
#  यह अनिवार्य है: अपनी स्प्लैश स्क्रीन का बैकग्राउंड कलर दें।
  color: "#FFFFFF"
#  यह अनिवार्य है: अपनी लोगो इमेज का पाथ दें।
  image: assets/icons/app_icon.png
#    (वैकल्पिक) Android 12 और उसके बाद के वर्ज़न के लिए, जहां एनिमेटेड स्प्लैश स्क्रीन होती है।
  android_12:
    color: "#FFFFFF"
    image: assets/icons/app_icon.png  # यदि आप Android 12 के लिए अलग इमेज चाहते हैं
    color_dark: "#000000" # Android 12 के लिए डार्क बैकग्राउंड
    image_dark: assets/icons/app_icon.png #  (वैकल्पिक) यदि आप dark mode के लिए अलग सेटअप चाहते हैं:


flutter_launcher_icons:
#  android: "launcher_icon"
  android: true
  image_path: "assets/icons/app_icon.png"

#----------------------------
flutter_gen:
  output: lib/core/flutter_gen_assets/ # Optional (default: lib/gen/)
  # line_length: 80 # Optional

  # Optional
#  integrations:
#    image: true
#    flutter_svg: true
#    lottie: true
#    rive: true
#    colors: true
#    fonts: true

# run this command if new assets added -> dart run build_runner build

#----------------------------

