import '../../library.dart';

class AppColorScheme {
  static ColorScheme lightScheme() {
    return const ColorScheme(
      // seedColor: Colors.purple,
      brightness: Brightness.light,
      primary: AppMaterialLightColors.primary,
      surfaceTint: AppMaterialLightColors.surfaceTint,
      onPrimary: AppMaterialLightColors.onPrimary,
      primaryContainer: AppMaterialLightColors.primaryContainer,
      onPrimaryContainer: AppMaterialLightColors.onPrimaryContainer,
      secondary: AppMaterialLightColors.secondary,
      onSecondary: AppMaterialLightColors.onSecondary,
      secondaryContainer: AppMaterialLightColors.secondaryContainer,
      onSecondaryContainer: AppMaterialLightColors.onSecondaryContainer,
      tertiary: AppMaterialLightColors.tertiary,
      onTertiary: AppMaterialLightColors.onTertiary,
      tertiaryContainer: AppMaterialLightColors.tertiaryContainer,
      onTertiaryContainer: AppMaterialLightColors.onTertiaryContainer,
      error: AppMaterialLightColors.error,
      onError: AppMaterialLightColors.onError,
      errorContainer: AppMaterialLightColors.errorContainer,
      onErrorContainer: AppMaterialLightColors.onErrorContainer,
      surface: AppMaterialLightColors.surface,
      onSurface: AppMaterialLightColors.onSurface,
      onSurfaceVariant: AppMaterialLightColors.onSurfaceVariant,
      outline: AppMaterialLightColors.outline,
      outlineVariant: AppMaterialLightColors.outlineVariant,
      shadow: AppMaterialLightColors.shadow,
      scrim: AppMaterialLightColors.scrim,
      inverseSurface: AppMaterialLightColors.inverseSurface,
      inversePrimary: AppMaterialLightColors.inversePrimary,
      primaryFixed: AppMaterialLightColors.primaryFixed,
      onPrimaryFixed: AppMaterialLightColors.onPrimaryFixed,
      primaryFixedDim: AppMaterialLightColors.primaryFixedDim,
      onPrimaryFixedVariant: AppMaterialLightColors.onPrimaryFixedVariant,
      secondaryFixed: AppMaterialLightColors.secondaryFixed,
      onSecondaryFixed: AppMaterialLightColors.onSecondaryFixed,
      secondaryFixedDim: AppMaterialLightColors.secondaryFixedDim,
      onSecondaryFixedVariant: AppMaterialLightColors.onSecondaryFixedVariant,
      tertiaryFixed: AppMaterialLightColors.tertiaryFixed,
      onTertiaryFixed: AppMaterialLightColors.onTertiaryFixed,
      tertiaryFixedDim: AppMaterialLightColors.tertiaryFixedDim,
      onTertiaryFixedVariant: AppMaterialLightColors.onTertiaryFixedVariant,
      surfaceDim: AppMaterialLightColors.surfaceDim,
      surfaceBright: AppMaterialLightColors.surfaceBright,
      surfaceContainerLowest: AppMaterialLightColors.surfaceContainerLowest,
      surfaceContainerLow: AppMaterialLightColors.surfaceContainerLow,
      surfaceContainer: AppMaterialLightColors.surfaceContainer,
      surfaceContainerHigh: AppMaterialLightColors.surfaceContainerHigh,
      surfaceContainerHighest: AppMaterialLightColors.surfaceContainerHighest,
    );
  }

  static ColorScheme darkScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: AppMaterialDarkColors.primary,
      surfaceTint: AppMaterialDarkColors.surfaceTint,
      onPrimary: AppMaterialDarkColors.onPrimary,
      primaryContainer: AppMaterialDarkColors.primaryContainer,
      onPrimaryContainer: AppMaterialDarkColors.onPrimaryContainer,
      secondary: AppMaterialDarkColors.secondary,
      onSecondary: AppMaterialDarkColors.onSecondary,
      secondaryContainer: AppMaterialDarkColors.secondaryContainer,
      onSecondaryContainer: AppMaterialDarkColors.onSecondaryContainer,
      tertiary: AppMaterialDarkColors.tertiary,
      onTertiary: AppMaterialDarkColors.onTertiary,
      tertiaryContainer: AppMaterialDarkColors.tertiaryContainer,
      onTertiaryContainer: AppMaterialDarkColors.onTertiaryContainer,
      error: AppMaterialDarkColors.error,
      onError: AppMaterialDarkColors.onError,
      errorContainer: AppMaterialDarkColors.errorContainer,
      onErrorContainer: AppMaterialDarkColors.onErrorContainer,
      surface: AppMaterialDarkColors.surface,
      onSurface: AppMaterialDarkColors.onSurface,
      onSurfaceVariant: AppMaterialDarkColors.onSurfaceVariant,
      outline: AppMaterialDarkColors.outline,
      outlineVariant: AppMaterialDarkColors.outlineVariant,
      shadow: AppMaterialDarkColors.shadow,
      scrim: AppMaterialDarkColors.scrim,
      inverseSurface: AppMaterialDarkColors.inverseSurface,
      inversePrimary: AppMaterialDarkColors.inversePrimary,
      primaryFixed: AppMaterialDarkColors.primaryFixed,
      onPrimaryFixed: AppMaterialDarkColors.onPrimaryFixed,
      primaryFixedDim: AppMaterialDarkColors.primaryFixedDim,
      onPrimaryFixedVariant: AppMaterialDarkColors.onPrimaryFixedVariant,
      secondaryFixed: AppMaterialDarkColors.secondaryFixed,
      onSecondaryFixed: AppMaterialDarkColors.onSecondaryFixed,
      secondaryFixedDim: AppMaterialDarkColors.secondaryFixedDim,
      onSecondaryFixedVariant: AppMaterialDarkColors.onSecondaryFixedVariant,
      tertiaryFixed: AppMaterialDarkColors.tertiaryFixed,
      onTertiaryFixed: AppMaterialDarkColors.onTertiaryFixed,
      tertiaryFixedDim: AppMaterialDarkColors.tertiaryFixedDim,
      onTertiaryFixedVariant: AppMaterialDarkColors.onTertiaryFixedVariant,
      surfaceDim: AppMaterialDarkColors.surfaceDim,
      surfaceBright: AppMaterialDarkColors.surfaceBright,
      surfaceContainerLowest: AppMaterialDarkColors.surfaceContainerLowest,
      surfaceContainerLow: AppMaterialDarkColors.surfaceContainerLow,
      surfaceContainer: AppMaterialDarkColors.surfaceContainer,
      surfaceContainerHigh: AppMaterialDarkColors.surfaceContainerHigh,
      surfaceContainerHighest: AppMaterialDarkColors.surfaceContainerHighest,
    );
  }
}
